version: "3"
services:
  selenium:
    image: selenium/standalone-chrome:4.0.0-rc-1-prerelease-20210823
    container_name: selenium-server
    ports:
      - 4444:4444
      - 7900:7900
    shm_size: 4gb
  app:
    build: .
    container_name: selenium-app
    volumes:
      - ./src:/usr/src
    environment:
      SELENIUM_URL: http://selenium:4444
    tty: true
